src/Django_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("posts.urls")),
]

src/posts/urls.py
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import path
from Django_blog import settings
from posts.views import *

app_name = "posts"
"""Cette variable est utile lorsque nous voulons
 rediriger vers une url de cette app , mais à la place nous pouvons aussi mettre un param
 namespace
dans notre fonction include """

urlpatterns = [
                  path('', BlogpostHome.as_view(), name='home'),
                  path('create/', BlogpostCreate.as_view(), name='create'),
                  path('edit/<str:slug>', login_required(BlogpostUpdate.as_view()), name='edit'),
                  path('<str:slug>/', BlogpostDetail.as_view(), name='detail'),
                  path('delete/<str:slug>/', BlogpostDelete.as_view(), name='delete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""L'ajout des fichiers static passe par cette dernierre ligne avec un "+" et la fonction static() """

src/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

User = get_user_model()


# Create your models here.

class Blogpost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbail = models.ImageField(blank=True, upload_to="blog")

    class Meta():
        ordering = ['-created_on']
        verbose_name = "Article"

    @property
    def author_or_default(self):
        return self.author.username if self.author else "End"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:home")

src/posts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import *

from posts.models import *


# Create your views here.

class BlogpostHome(ListView):
    # queryset = Blogpost.objects.filter(published=True)
    model = Blogpost
    context_object_name = "posts"
    template_name = "posts/index.html"


class BlogpostCreate(CreateView):
    model = Blogpost
    template_name = "posts/create.html"
    fields = ["title", "content", ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Créer"
        return context


class BlogpostUpdate(UpdateView):
    model = Blogpost
    template_name = "posts/create.html"
    fields = ["title", "content", "published", ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["title"] = "Editer"
        return context


class BlogpostDelete(DeleteView):
    model = Blogpost
    template_name = "posts/delete.html"
    fields = ["title", "content", ]
    success_url = reverse_lazy("posts:home")
    context_object_name = "post"



class BlogpostDetail(DetailView):
    model = Blogpost
    template_name = "posts/detail.html"
    fields = ["title", "content", ]
    context_object_name = "post"

src/posts/templates/posts/create.html
{% extends 'base.html' %}
{% block title%}
<title>{{ title }} un article</title>
{% endblock %}

{% block content %}
<h1>{{ title }}  un article</h1>
<form method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <br>
    <input class="btn-submit" type="submit" value="{{ title }} ">
</form>

{% endblock %}

src/posts/templates/posts/delete.html
{% extends 'base.html' %}
{% block title%}
<title>Suppression de l'article "{{post.title}}"</title>
{% endblock %}

{% block content %}
<form method="post">
  {% csrf_token %}
  <p>Voulez vous vraiment supprimer "{{post.title}}"?</p>
  <input class="btn btn-delete" type="submit" value="Oui, Supprimer">
</form>
{% endblock %}

src/posts/templates/posts/detail.html
{% extends 'base.html' %}
{% block title%}
<title>{{post.title}}</title>
{% endblock %}

{% block content %}
 <article>
   <h1><a href=""></a>{{post.title}}</h1>
     <hr>
     <img src="{{ post.thumbail.url }}" alt="image de l'article">
     <hr>

     <br><br>
     <hr>
   <div class="post-detail"><p>{{post.content|safe|linebreaks}}</p></div>
 </article>


{% endblock %}

src/posts/templates/posts/index.html
{% extends 'base.html' %}
{% block title%}
<title>Accueil du blog</title>
{% endblock %}
<!--Ici on arrive pas à acceder à notre base de données car rien n'est creer comme article donc il n'y a pas exactement de probleme ,
il suffit donc de céer quelques articles dans notre BD-->
{% block content %}
<h1>Le blog des Ruines du savoir</h1>
<main >
{% for post in posts %}
<article>
<div class ="post-title"> {% if request.user.is_authenticated %}
    <a href="{% url 'posts:edit' post.slug %}">Editer</a><br>
    <hr>
    <a href="{% url 'posts:delete' post.slug %}">Supprime</a>

    {% endif %}
</div>

    <div>
        <h2 style="color:wheat;text-align:center;margin:40px;">{{ post.title|upper }}</h2>

        <h5 class="post-author" style="color:white;">Publié par <i>{{post.author_or_default}}</i> le <small>{{post.created_on|date:'j F Y' }}</small></h5>
    <p class="post-content">{{post.content|safe|truncatewords:30}}</p>
</div>
    <form action="{% url 'posts:detail' post.slug %}" >
    <button class="btn btn-submit">Lire l'arlicle</button>
        </form>
</article>
    {% endfor %}
</main>
{% endblock %}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title %}
    <title>Les ruines du savoir...</title>
    {% endblock%}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav><a href="{% url 'posts:home' %}">Accueil</a><br>
    <hr>
    <br>
    {% if request.user.is_authenticated %}
    <a href="{% url 'posts:create' %}">Ajouter un article</a>
    
    {% endif %}
</nav>
    <section id="blog">
        {% block content %}

        {% endblock %}
    </section>
</body>
</html>